# Generated by Django 4.2.14 on 2024-07-21 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashCollector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="balance",
                    ),
                ),
                ("frozen", models.BooleanField(default=False, verbose_name="frozen")),
                (
                    "last_collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last collected date time"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_collector",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Collector",
                "verbose_name_plural": "Cash Collectors",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="collected at"
                    ),
                ),
                (
                    "delivered",
                    models.BooleanField(default=False, verbose_name="delivered"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="customer name"),
                ),
                (
                    "customer_address",
                    models.CharField(max_length=255, verbose_name="customer address"),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount due"
                    ),
                ),
                ("amount_due_at", models.DateTimeField()),
                (
                    "collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="collected at"
                    ),
                ),
                (
                    "cash_collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="collection.cashcollector",
                        verbose_name="cash collector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["amount_due_at"],
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager",
                "verbose_name_plural": "Managers",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        to="collection.collection",
                        verbose_name="collections",
                    ),
                ),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="collection.cashcollector",
                        verbose_name="collector",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries_received",
                        to="collection.manager",
                        verbose_name="manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
                "ordering": ["-delivered_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="creation date")),
                ("status", models.BooleanField(verbose_name="status")),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="collection.cashcollector",
                        verbose_name="collector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Log",
                "verbose_name_plural": "Collection Logs",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="collection.task",
                verbose_name="task",
            ),
        ),
    ]
