name: Cash Collection Backend CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: cash
          POSTGRES_PASSWORD: passw0rd
          POSTGRES_DB: cash
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test PostgreSQL Connection
      run: |
        sudo apt-get update && sudo apt-get install -y postgresql-client
        PGPASSWORD="passw0rd" psql -h localhost -U cash -d cash -c "\dt"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.7'

    - name: Install system dependencies
      run: |
        sudo apt-get -q update
        sudo apt-get install -y gcc python3-dev libpq-dev
        sudo apt-get install -y cron
        sudo touch /var/log/cron.log
        sudo service cron start

    - name: Install Python dependencies
      run: |
        pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Prepare environment
      run: |
        sed '/^POSTGRES_HOST/d' .env.example >> .env
        echo POSTGRES_HOST=localhost >> .env

    - name: Run Django migrations and checks
      run: |
        python manage.py migrate
        python manage.py check
        python manage.py makemigrations --check --dry-run collection

    - name: Run Django Unit Test
      run: |
        coverage run manage.py test
        coverage report
